version: '3.8'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3000"
  server:
    restart: unless-stopped
    env_file: ./.env
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    links:
       - mongodb
    # environment:
    #   - MONGO_URI=mongodb://root:example@mongo:27017/urlShortener
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongo-db:/docker-entrypoint-initdb.d
    #  - db:/data/db